baseURL: https://blog.ous50.moe/
# languageCode: en-us
title: ousfifty's blog
theme: stack
paginate: 5

params:
    author: ousfifty
    email: me at ous50.moe

services:
  disqus:
    shortname: ""
  googleAnalytics:
    # id: "G-WPFE7HNMC5"
    id: "GTM-W6V7TWF9"
  instagram:
    accessToken: ""
    disableInlineCSS: false
  rss:
    limit: -1
  twitter:
    disableInlineCSS: false

languages:
  en:
    languageName: English
    params:
        title: ousfifty's blog
        subtitle: OwO
        owner: ousfifty
        keywords: tech
        copyright: 'ousfifty 2020-'
        menuMore: Show more
        readMore: Read more
        readOtherPosts: Read other posts
        missingContentMessage: Page not found..
        missingBackButtonLabel: Back to home page
  zh-cn:
    languageName: 简体中文
    params:
        title: 欧式fifty 的 blog
        subtitle: OwO
        owner: 欧式fifty
        keywords: tech
        copyright: '欧式fifty 2020-'
        menuMore: 显示更多
        readMore: 阅读全文
        readOtherPosts: 看看别的
        missingContentMessage: 找不到页面...
        missingBackButtonLabel: 返回主页
  yue-cn:
    languageName: 广东话
    params:
        title: 欧式fifty 嘅 blog
        subtitle: OwO
        owner: 欧式fifty
        keywords: tech
        copyright: '欧式fifty 2020-'
        menuMore: 显示更多
        readMore: 阅读全文
        readOtherPosts: 睇下其他
        missingContentMessage: 揾不到页面...
        missingBackButtonLabel: 返到主页

  # GA Tracking ID
# googleAnalytics: G-WPFE7HNMC5

enableRobotsTXT:
  true
  # Theme i18n support
  # Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage:  'zh-cn'

  # Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
  # This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: /favicon.ico # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

  footer:
    since: 2020
    customText: OwO

  dateFormat:
    published: Jan 02, 2006 15:04 HKT
    lastUpdated: Jan 02, 2006 15:04 HKT

  sidebar:
    emoji:
    subtitle:
    # avatar:
    #     enabled: true
    #     local: true
    #     src: images/avatar.webp

  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: disqusjs

    disqusjs:
      shortname: ousfifty
      apiUrl: https://disqus.skk.moe/disqus/
      apiKey: KCir2w9VCAOu1FenHGVqTZERzhy9zLTtFZIRxMCp8YQrD5sJiHGKg6CvWa27I1ta
      admin: ousfifty
      adminLabel: Author

    utterances:
      repo:
      issueTerm: pathname
      label:

    remark42:
      host:
      site:
      locale:

    vssue:
      platform:
      owner:
      repo:
      clientId:
      clientSecret:
      autoCreateIssue: false

    # Waline client configuration see: https://waline.js.org/en/reference/component.html
    waline:
      serverURL:
      lang:
      pageview:
      emoji:
        - https://unpkg.com/@waline/emojis@1.0.1/weibo
      requiredMeta:
        - name
        - email
        - url
      locale:
        admin: Admin
        placeholder:

    twikoo:
      envId:
      region:
      path:
      lang:

    # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
    cactus:
      defaultHomeserverUrl: 'https://matrix.cactus.chat:8448'
      serverName: 'cactus.chat'
      siteName: '' # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

    giscus:
      repo:
      repoID:
      category:
      categoryID:
      mapping:
      lightTheme:
      darkTheme:
      reactionsEnabled: 1
      emitMetadata: 0

    gitalk:
      owner:
      admin:
      repo:
      clientID:
      clientSecret:

    cusdis:
      host:
      id:
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site:

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

  ### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: []

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/CaiJimmy/ous50
      params:
        icon: brand-github

    - identifier: twitter
      name: Twitter
      url: https://twitter.com/ousfifty
      params:
        icon: brand-twitter

    - identifier: rss
      name: RSS
      url: index.xml
      params:
        icon: rss

    - identifier: telegram
      name: Telegram
      url: https://ous50.t.me
      params:
        icon: messages

    - identifier: pgp
      name: PGP key
      url: https://fars.ee/Bm08
      params:
        icon: messages

    - identifier: sitemap
      name: Sitemap
      url: sitemap.xml

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4

sitemap:
  changefreq: always
  priority: 0.5
